// Code generated by protoc-gen-go. DO NOT EDIT.
// source: client/rpc/types/types.proto

package types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	config "github.com/nymtech/nym-mixnet/config"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	// Types that are valid to be assigned to Value:
	//	*Request_Send
	//	*Request_Fetch
	//	*Request_Flush
	Value                isRequest_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ce088dbf8865287, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

type isRequest_Value interface {
	isRequest_Value()
}

type Request_Send struct {
	Send *RequestSendMessage `protobuf:"bytes,2,opt,name=send,proto3,oneof"`
}

type Request_Fetch struct {
	Fetch *RequestFetchMessages `protobuf:"bytes,3,opt,name=fetch,proto3,oneof"`
}

type Request_Flush struct {
	Flush *RequestFlush `protobuf:"bytes,4,opt,name=flush,proto3,oneof"`
}

func (*Request_Send) isRequest_Value() {}

func (*Request_Fetch) isRequest_Value() {}

func (*Request_Flush) isRequest_Value() {}

func (m *Request) GetValue() isRequest_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Request) GetSend() *RequestSendMessage {
	if x, ok := m.GetValue().(*Request_Send); ok {
		return x.Send
	}
	return nil
}

func (m *Request) GetFetch() *RequestFetchMessages {
	if x, ok := m.GetValue().(*Request_Fetch); ok {
		return x.Fetch
	}
	return nil
}

func (m *Request) GetFlush() *RequestFlush {
	if x, ok := m.GetValue().(*Request_Flush); ok {
		return x.Flush
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Request) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Request_Send)(nil),
		(*Request_Fetch)(nil),
		(*Request_Flush)(nil),
	}
}

type RequestSendMessage struct {
	Message              []byte               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Recipient            *config.ClientConfig `protobuf:"bytes,2,opt,name=recipient,proto3" json:"recipient,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RequestSendMessage) Reset()         { *m = RequestSendMessage{} }
func (m *RequestSendMessage) String() string { return proto.CompactTextString(m) }
func (*RequestSendMessage) ProtoMessage()    {}
func (*RequestSendMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ce088dbf8865287, []int{1}
}

func (m *RequestSendMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestSendMessage.Unmarshal(m, b)
}
func (m *RequestSendMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestSendMessage.Marshal(b, m, deterministic)
}
func (m *RequestSendMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestSendMessage.Merge(m, src)
}
func (m *RequestSendMessage) XXX_Size() int {
	return xxx_messageInfo_RequestSendMessage.Size(m)
}
func (m *RequestSendMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestSendMessage.DiscardUnknown(m)
}

var xxx_messageInfo_RequestSendMessage proto.InternalMessageInfo

func (m *RequestSendMessage) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *RequestSendMessage) GetRecipient() *config.ClientConfig {
	if m != nil {
		return m.Recipient
	}
	return nil
}

type RequestFetchMessages struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestFetchMessages) Reset()         { *m = RequestFetchMessages{} }
func (m *RequestFetchMessages) String() string { return proto.CompactTextString(m) }
func (*RequestFetchMessages) ProtoMessage()    {}
func (*RequestFetchMessages) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ce088dbf8865287, []int{2}
}

func (m *RequestFetchMessages) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestFetchMessages.Unmarshal(m, b)
}
func (m *RequestFetchMessages) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestFetchMessages.Marshal(b, m, deterministic)
}
func (m *RequestFetchMessages) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestFetchMessages.Merge(m, src)
}
func (m *RequestFetchMessages) XXX_Size() int {
	return xxx_messageInfo_RequestFetchMessages.Size(m)
}
func (m *RequestFetchMessages) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestFetchMessages.DiscardUnknown(m)
}

var xxx_messageInfo_RequestFetchMessages proto.InternalMessageInfo

type RequestFlush struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestFlush) Reset()         { *m = RequestFlush{} }
func (m *RequestFlush) String() string { return proto.CompactTextString(m) }
func (*RequestFlush) ProtoMessage()    {}
func (*RequestFlush) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ce088dbf8865287, []int{3}
}

func (m *RequestFlush) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestFlush.Unmarshal(m, b)
}
func (m *RequestFlush) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestFlush.Marshal(b, m, deterministic)
}
func (m *RequestFlush) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestFlush.Merge(m, src)
}
func (m *RequestFlush) XXX_Size() int {
	return xxx_messageInfo_RequestFlush.Size(m)
}
func (m *RequestFlush) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestFlush.DiscardUnknown(m)
}

var xxx_messageInfo_RequestFlush proto.InternalMessageInfo

type Response struct {
	// Types that are valid to be assigned to Value:
	//	*Response_Exception
	//	*Response_Send
	//	*Response_Fetch
	//	*Response_Flush
	Value                isResponse_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ce088dbf8865287, []int{4}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

type isResponse_Value interface {
	isResponse_Value()
}

type Response_Exception struct {
	Exception *ResponseException `protobuf:"bytes,1,opt,name=exception,proto3,oneof"`
}

type Response_Send struct {
	Send *ResponseSendMessage `protobuf:"bytes,2,opt,name=send,proto3,oneof"`
}

type Response_Fetch struct {
	Fetch *ResponseFetchMessages `protobuf:"bytes,3,opt,name=fetch,proto3,oneof"`
}

type Response_Flush struct {
	Flush *ResponseFlush `protobuf:"bytes,4,opt,name=flush,proto3,oneof"`
}

func (*Response_Exception) isResponse_Value() {}

func (*Response_Send) isResponse_Value() {}

func (*Response_Fetch) isResponse_Value() {}

func (*Response_Flush) isResponse_Value() {}

func (m *Response) GetValue() isResponse_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Response) GetException() *ResponseException {
	if x, ok := m.GetValue().(*Response_Exception); ok {
		return x.Exception
	}
	return nil
}

func (m *Response) GetSend() *ResponseSendMessage {
	if x, ok := m.GetValue().(*Response_Send); ok {
		return x.Send
	}
	return nil
}

func (m *Response) GetFetch() *ResponseFetchMessages {
	if x, ok := m.GetValue().(*Response_Fetch); ok {
		return x.Fetch
	}
	return nil
}

func (m *Response) GetFlush() *ResponseFlush {
	if x, ok := m.GetValue().(*Response_Flush); ok {
		return x.Flush
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Response) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Response_Exception)(nil),
		(*Response_Send)(nil),
		(*Response_Fetch)(nil),
		(*Response_Flush)(nil),
	}
}

type ResponseException struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseException) Reset()         { *m = ResponseException{} }
func (m *ResponseException) String() string { return proto.CompactTextString(m) }
func (*ResponseException) ProtoMessage()    {}
func (*ResponseException) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ce088dbf8865287, []int{5}
}

func (m *ResponseException) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseException.Unmarshal(m, b)
}
func (m *ResponseException) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseException.Marshal(b, m, deterministic)
}
func (m *ResponseException) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseException.Merge(m, src)
}
func (m *ResponseException) XXX_Size() int {
	return xxx_messageInfo_ResponseException.Size(m)
}
func (m *ResponseException) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseException.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseException proto.InternalMessageInfo

func (m *ResponseException) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ResponseSendMessage struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseSendMessage) Reset()         { *m = ResponseSendMessage{} }
func (m *ResponseSendMessage) String() string { return proto.CompactTextString(m) }
func (*ResponseSendMessage) ProtoMessage()    {}
func (*ResponseSendMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ce088dbf8865287, []int{6}
}

func (m *ResponseSendMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseSendMessage.Unmarshal(m, b)
}
func (m *ResponseSendMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseSendMessage.Marshal(b, m, deterministic)
}
func (m *ResponseSendMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseSendMessage.Merge(m, src)
}
func (m *ResponseSendMessage) XXX_Size() int {
	return xxx_messageInfo_ResponseSendMessage.Size(m)
}
func (m *ResponseSendMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseSendMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseSendMessage proto.InternalMessageInfo

type ResponseFlush struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseFlush) Reset()         { *m = ResponseFlush{} }
func (m *ResponseFlush) String() string { return proto.CompactTextString(m) }
func (*ResponseFlush) ProtoMessage()    {}
func (*ResponseFlush) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ce088dbf8865287, []int{7}
}

func (m *ResponseFlush) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseFlush.Unmarshal(m, b)
}
func (m *ResponseFlush) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseFlush.Marshal(b, m, deterministic)
}
func (m *ResponseFlush) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseFlush.Merge(m, src)
}
func (m *ResponseFlush) XXX_Size() int {
	return xxx_messageInfo_ResponseFlush.Size(m)
}
func (m *ResponseFlush) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseFlush.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseFlush proto.InternalMessageInfo

type ResponseFetchMessages struct {
	Messages             [][]byte `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseFetchMessages) Reset()         { *m = ResponseFetchMessages{} }
func (m *ResponseFetchMessages) String() string { return proto.CompactTextString(m) }
func (*ResponseFetchMessages) ProtoMessage()    {}
func (*ResponseFetchMessages) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ce088dbf8865287, []int{8}
}

func (m *ResponseFetchMessages) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseFetchMessages.Unmarshal(m, b)
}
func (m *ResponseFetchMessages) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseFetchMessages.Marshal(b, m, deterministic)
}
func (m *ResponseFetchMessages) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseFetchMessages.Merge(m, src)
}
func (m *ResponseFetchMessages) XXX_Size() int {
	return xxx_messageInfo_ResponseFetchMessages.Size(m)
}
func (m *ResponseFetchMessages) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseFetchMessages.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseFetchMessages proto.InternalMessageInfo

func (m *ResponseFetchMessages) GetMessages() [][]byte {
	if m != nil {
		return m.Messages
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "types.Request")
	proto.RegisterType((*RequestSendMessage)(nil), "types.RequestSendMessage")
	proto.RegisterType((*RequestFetchMessages)(nil), "types.RequestFetchMessages")
	proto.RegisterType((*RequestFlush)(nil), "types.RequestFlush")
	proto.RegisterType((*Response)(nil), "types.Response")
	proto.RegisterType((*ResponseException)(nil), "types.ResponseException")
	proto.RegisterType((*ResponseSendMessage)(nil), "types.ResponseSendMessage")
	proto.RegisterType((*ResponseFlush)(nil), "types.ResponseFlush")
	proto.RegisterType((*ResponseFetchMessages)(nil), "types.ResponseFetchMessages")
}

func init() { proto.RegisterFile("client/rpc/types/types.proto", fileDescriptor_3ce088dbf8865287) }

var fileDescriptor_3ce088dbf8865287 = []byte{
	// 354 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xc1, 0x4e, 0xf2, 0x40,
	0x14, 0x85, 0xe9, 0x0f, 0xfd, 0x81, 0x0b, 0x6a, 0x1c, 0x8a, 0xa9, 0xc8, 0x82, 0xcc, 0x0a, 0xa3,
	0x69, 0x0d, 0xb8, 0x70, 0x2d, 0xd1, 0xb0, 0x71, 0x33, 0x3e, 0x01, 0x0c, 0x17, 0x68, 0x82, 0x6d,
	0x9d, 0x99, 0x1a, 0x7d, 0x20, 0x9f, 0xcc, 0x17, 0x31, 0x9d, 0x29, 0x60, 0x4b, 0xd9, 0x34, 0x73,
	0x73, 0xce, 0x69, 0xcf, 0xfd, 0x3a, 0xd0, 0xe7, 0x9b, 0x00, 0x43, 0xe5, 0x8b, 0x98, 0xfb, 0xea,
	0x2b, 0x46, 0x69, 0x9e, 0x5e, 0x2c, 0x22, 0x15, 0x11, 0x5b, 0x0f, 0x3d, 0x87, 0x47, 0xe1, 0x32,
	0x58, 0xf9, 0x52, 0x89, 0x84, 0xab, 0x4c, 0xa4, 0xdf, 0x16, 0xd4, 0x19, 0xbe, 0x27, 0x28, 0x15,
	0xf1, 0xa1, 0x26, 0x31, 0x5c, 0xb8, 0xff, 0x06, 0xd6, 0xb0, 0x35, 0xba, 0xf4, 0xcc, 0x4b, 0x32,
	0xf5, 0x15, 0xc3, 0xc5, 0x0b, 0x4a, 0x39, 0x5b, 0xe1, 0xb4, 0xc2, 0xb4, 0x91, 0x8c, 0xc1, 0x5e,
	0xa2, 0xe2, 0x6b, 0xb7, 0xaa, 0x13, 0x57, 0xf9, 0xc4, 0x73, 0x2a, 0x65, 0x11, 0x39, 0xad, 0x30,
	0xe3, 0x25, 0x37, 0x60, 0x2f, 0x37, 0x89, 0x5c, 0xbb, 0x35, 0x1d, 0xea, 0x14, 0x42, 0xa9, 0xa4,
	0xcd, 0xe9, 0xe1, 0xb1, 0x0e, 0xf6, 0xc7, 0x6c, 0x93, 0x20, 0x9d, 0x03, 0x39, 0x2c, 0x42, 0x5c,
	0xa8, 0xbf, 0x99, 0xa3, 0x6b, 0x0d, 0xac, 0x61, 0x9b, 0x6d, 0x47, 0x32, 0x82, 0xa6, 0x40, 0x1e,
	0xc4, 0x29, 0x97, 0x6c, 0x21, 0xc7, 0x33, 0x04, 0xbc, 0x89, 0xa6, 0x35, 0xd1, 0x03, 0xdb, 0xdb,
	0xe8, 0x05, 0x38, 0x65, 0xd5, 0xe9, 0x29, 0xb4, 0xff, 0xb6, 0xa3, 0x3f, 0x16, 0x34, 0x18, 0xca,
	0x38, 0x0a, 0x25, 0x92, 0x07, 0x68, 0xe2, 0x27, 0xc7, 0x58, 0x05, 0x51, 0xa8, 0x4b, 0xb4, 0x46,
	0xee, 0x6e, 0x25, 0xe3, 0x79, 0xda, 0xea, 0xd3, 0x0a, 0xdb, 0x9b, 0xc9, 0x5d, 0x0e, 0x77, 0xaf,
	0x10, 0x2a, 0xe3, 0x7d, 0x9f, 0xe7, 0xdd, 0x2f, 0x44, 0x8e, 0x00, 0xbf, 0xcd, 0x03, 0x77, 0x8a,
	0xa9, 0x23, 0xc4, 0xaf, 0xe1, 0xfc, 0x60, 0x01, 0xe2, 0x80, 0x8d, 0x42, 0x44, 0x42, 0x6f, 0xda,
	0x64, 0x66, 0xa0, 0x5d, 0xe8, 0x94, 0xd4, 0xa6, 0x67, 0x70, 0x92, 0xfb, 0x08, 0x1d, 0x43, 0xb7,
	0xb4, 0x2b, 0xe9, 0x41, 0x23, 0xfb, 0x71, 0xd2, 0xb5, 0x06, 0xd5, 0x61, 0x9b, 0xed, 0xe6, 0xf9,
	0x7f, 0x7d, 0x51, 0xc7, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xed, 0x1b, 0xa8, 0x69, 0xe5, 0x02,
	0x00, 0x00,
}
