// Code generated by protoc-gen-go. DO NOT EDIT.
// source: config/structs.proto

package config

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MixConfig struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,json=id,proto3" json:"Id,omitempty"`
	Host                 string   `protobuf:"bytes,2,opt,name=Host,json=host,proto3" json:"Host,omitempty"`
	Port                 string   `protobuf:"bytes,3,opt,name=Port,json=port,proto3" json:"Port,omitempty"`
	PubKey               []byte   `protobuf:"bytes,4,opt,name=PubKey,json=pubKey,proto3" json:"PubKey,omitempty"`
	Layer                uint64   `protobuf:"varint,5,opt,name=Layer,json=layer,proto3" json:"Layer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MixConfig) Reset()         { *m = MixConfig{} }
func (m *MixConfig) String() string { return proto.CompactTextString(m) }
func (*MixConfig) ProtoMessage()    {}
func (*MixConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9a12e0597d01ddf, []int{0}
}

func (m *MixConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MixConfig.Unmarshal(m, b)
}
func (m *MixConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MixConfig.Marshal(b, m, deterministic)
}
func (m *MixConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MixConfig.Merge(m, src)
}
func (m *MixConfig) XXX_Size() int {
	return xxx_messageInfo_MixConfig.Size(m)
}
func (m *MixConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_MixConfig.DiscardUnknown(m)
}

var xxx_messageInfo_MixConfig proto.InternalMessageInfo

func (m *MixConfig) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MixConfig) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *MixConfig) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *MixConfig) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *MixConfig) GetLayer() uint64 {
	if m != nil {
		return m.Layer
	}
	return 0
}

type ClientConfig struct {
	Id                   string     `protobuf:"bytes,1,opt,name=Id,json=id,proto3" json:"Id,omitempty"`
	Host                 string     `protobuf:"bytes,2,opt,name=Host,json=host,proto3" json:"Host,omitempty"`
	Port                 string     `protobuf:"bytes,3,opt,name=Port,json=port,proto3" json:"Port,omitempty"`
	PubKey               []byte     `protobuf:"bytes,4,opt,name=PubKey,json=pubKey,proto3" json:"PubKey,omitempty"`
	Provider             *MixConfig `protobuf:"bytes,5,opt,name=Provider,json=provider,proto3" json:"Provider,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ClientConfig) Reset()         { *m = ClientConfig{} }
func (m *ClientConfig) String() string { return proto.CompactTextString(m) }
func (*ClientConfig) ProtoMessage()    {}
func (*ClientConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9a12e0597d01ddf, []int{1}
}

func (m *ClientConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientConfig.Unmarshal(m, b)
}
func (m *ClientConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientConfig.Marshal(b, m, deterministic)
}
func (m *ClientConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientConfig.Merge(m, src)
}
func (m *ClientConfig) XXX_Size() int {
	return xxx_messageInfo_ClientConfig.Size(m)
}
func (m *ClientConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ClientConfig proto.InternalMessageInfo

func (m *ClientConfig) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ClientConfig) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *ClientConfig) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *ClientConfig) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *ClientConfig) GetProvider() *MixConfig {
	if m != nil {
		return m.Provider
	}
	return nil
}

type GeneralPacket struct {
	Flag                 []byte   `protobuf:"bytes,1,opt,name=Flag,json=flag,proto3" json:"Flag,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=Data,json=data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GeneralPacket) Reset()         { *m = GeneralPacket{} }
func (m *GeneralPacket) String() string { return proto.CompactTextString(m) }
func (*GeneralPacket) ProtoMessage()    {}
func (*GeneralPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9a12e0597d01ddf, []int{2}
}

func (m *GeneralPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeneralPacket.Unmarshal(m, b)
}
func (m *GeneralPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeneralPacket.Marshal(b, m, deterministic)
}
func (m *GeneralPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeneralPacket.Merge(m, src)
}
func (m *GeneralPacket) XXX_Size() int {
	return xxx_messageInfo_GeneralPacket.Size(m)
}
func (m *GeneralPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_GeneralPacket.DiscardUnknown(m)
}

var xxx_messageInfo_GeneralPacket proto.InternalMessageInfo

func (m *GeneralPacket) GetFlag() []byte {
	if m != nil {
		return m.Flag
	}
	return nil
}

func (m *GeneralPacket) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type ProviderResponse struct {
	NumberOfPackets      uint64   `protobuf:"varint,1,opt,name=NumberOfPackets,json=numberOfPackets,proto3" json:"NumberOfPackets,omitempty"`
	Packets              [][]byte `protobuf:"bytes,2,rep,name=Packets,json=packets,proto3" json:"Packets,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProviderResponse) Reset()         { *m = ProviderResponse{} }
func (m *ProviderResponse) String() string { return proto.CompactTextString(m) }
func (*ProviderResponse) ProtoMessage()    {}
func (*ProviderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9a12e0597d01ddf, []int{3}
}

func (m *ProviderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProviderResponse.Unmarshal(m, b)
}
func (m *ProviderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProviderResponse.Marshal(b, m, deterministic)
}
func (m *ProviderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProviderResponse.Merge(m, src)
}
func (m *ProviderResponse) XXX_Size() int {
	return xxx_messageInfo_ProviderResponse.Size(m)
}
func (m *ProviderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProviderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProviderResponse proto.InternalMessageInfo

func (m *ProviderResponse) GetNumberOfPackets() uint64 {
	if m != nil {
		return m.NumberOfPackets
	}
	return 0
}

func (m *ProviderResponse) GetPackets() [][]byte {
	if m != nil {
		return m.Packets
	}
	return nil
}

type PullRequest struct {
	Token                []byte   `protobuf:"bytes,1,opt,name=Token,json=token,proto3" json:"Token,omitempty"`
	ClientPublicKey      []byte   `protobuf:"bytes,2,opt,name=ClientPublicKey,json=clientPublicKey,proto3" json:"ClientPublicKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PullRequest) Reset()         { *m = PullRequest{} }
func (m *PullRequest) String() string { return proto.CompactTextString(m) }
func (*PullRequest) ProtoMessage()    {}
func (*PullRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9a12e0597d01ddf, []int{4}
}

func (m *PullRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullRequest.Unmarshal(m, b)
}
func (m *PullRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullRequest.Marshal(b, m, deterministic)
}
func (m *PullRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullRequest.Merge(m, src)
}
func (m *PullRequest) XXX_Size() int {
	return xxx_messageInfo_PullRequest.Size(m)
}
func (m *PullRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PullRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PullRequest proto.InternalMessageInfo

func (m *PullRequest) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *PullRequest) GetClientPublicKey() []byte {
	if m != nil {
		return m.ClientPublicKey
	}
	return nil
}

func init() {
	proto.RegisterType((*MixConfig)(nil), "config.MixConfig")
	proto.RegisterType((*ClientConfig)(nil), "config.ClientConfig")
	proto.RegisterType((*GeneralPacket)(nil), "config.GeneralPacket")
	proto.RegisterType((*ProviderResponse)(nil), "config.ProviderResponse")
	proto.RegisterType((*PullRequest)(nil), "config.PullRequest")
}

func init() { proto.RegisterFile("config/structs.proto", fileDescriptor_f9a12e0597d01ddf) }

var fileDescriptor_f9a12e0597d01ddf = []byte{
	// 317 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x91, 0xcb, 0x4e, 0xf3, 0x30,
	0x10, 0x85, 0x95, 0xd4, 0x49, 0xdb, 0x69, 0xfe, 0xbf, 0x60, 0x55, 0x28, 0xcb, 0x28, 0xab, 0x6c,
	0x28, 0x12, 0x2c, 0x78, 0x80, 0x22, 0x2e, 0x82, 0x42, 0x64, 0x21, 0xf6, 0x4e, 0xe2, 0x96, 0xa8,
	0x26, 0x4e, 0x7d, 0x41, 0xf4, 0x21, 0x78, 0x67, 0x64, 0xbb, 0x45, 0xea, 0x03, 0xb0, 0x3c, 0x9f,
	0x46, 0x73, 0xce, 0x9c, 0x81, 0x59, 0x2d, 0xba, 0x55, 0xbb, 0xbe, 0x50, 0x5a, 0x9a, 0x5a, 0xab,
	0x79, 0x2f, 0x85, 0x16, 0x38, 0xf6, 0x34, 0xdf, 0xc2, 0x78, 0xd9, 0x7e, 0x2d, 0x9c, 0xc0, 0xff,
	0x21, 0x7c, 0x68, 0xd2, 0x20, 0x0b, 0x8a, 0x31, 0x09, 0xdb, 0x06, 0x63, 0x40, 0xf7, 0x42, 0xe9,
	0x34, 0x74, 0x04, 0xbd, 0x0b, 0xa5, 0x2d, 0x2b, 0x85, 0xd4, 0xe9, 0xc0, 0xb3, 0x5e, 0x48, 0x8d,
	0xcf, 0x20, 0x2e, 0x4d, 0xf5, 0xc8, 0x76, 0x29, 0xca, 0x82, 0x22, 0x21, 0x71, 0xef, 0x14, 0x9e,
	0x41, 0xf4, 0x44, 0x77, 0x4c, 0xa6, 0x51, 0x16, 0x14, 0x88, 0x44, 0xdc, 0x8a, 0xfc, 0x3b, 0x80,
	0x64, 0xc1, 0x5b, 0xd6, 0xe9, 0x3f, 0xb2, 0x3d, 0x87, 0x51, 0x29, 0xc5, 0x67, 0xdb, 0xec, 0x9d,
	0x27, 0x97, 0xa7, 0x73, 0x7f, 0xee, 0xfc, 0xf7, 0x56, 0x32, 0xea, 0xf7, 0x23, 0xf9, 0x35, 0xfc,
	0xbb, 0x63, 0x1d, 0x93, 0x94, 0x97, 0xb4, 0xde, 0x30, 0xe7, 0x75, 0xcb, 0xe9, 0xda, 0x25, 0x4a,
	0x08, 0x5a, 0x71, 0xba, 0xb6, 0xec, 0x86, 0x6a, 0xea, 0x32, 0x25, 0x04, 0x35, 0x54, 0xd3, 0xfc,
	0x0d, 0x4e, 0x0e, 0x3e, 0x84, 0xa9, 0x5e, 0x74, 0x8a, 0xe1, 0x02, 0xa6, 0xcf, 0xe6, 0xa3, 0x62,
	0xf2, 0x65, 0xe5, 0xb7, 0x29, 0xb7, 0x06, 0x91, 0x69, 0x77, 0x8c, 0x71, 0x0a, 0xc3, 0xc3, 0x44,
	0x98, 0x0d, 0x8a, 0x84, 0x0c, 0x7b, 0x2f, 0xf3, 0x25, 0x4c, 0x4a, 0xc3, 0x39, 0x61, 0x5b, 0xc3,
	0x94, 0xb6, 0x2d, 0xbe, 0x8a, 0x0d, 0xeb, 0xf6, 0x79, 0x22, 0x6d, 0x85, 0x35, 0xf2, 0x25, 0x96,
	0xa6, 0xe2, 0x6d, 0x6d, 0x5b, 0xf0, 0xd9, 0xa6, 0xf5, 0x31, 0xae, 0x62, 0xf7, 0xf1, 0xab, 0x9f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x17, 0xe5, 0x0a, 0x17, 0x09, 0x02, 0x00, 0x00,
}
